### ISSUE TITLE
use "pronoun" instead of "gender" or "sex"

### ISSUE THREAD

**Issue by graingert** [sethblack/py-gift-exchange#2]
And allow pronoun to be any string

**Comment by new-guy** [comment]
How would you convert said pronoun into a value between 1 and 0?

**Comment by graingert** [comment]
> How would you convert said pronoun into a value between 1 and 0?

Sort all the input pronouns alphabetically and apply a number based on index evenly spaced between 0 and 1

**Comment by sethblack** [comment]
Aw man, the original post was deleted. I'll put my response here though for anyone wondering.

I specifically used sex because it is a very concrete scientific term. I feel like gender is something that can be chosen by the individual and can definitely change over time. Sex, however is fairly concrete, in that we only have XX or XY sex chromosomes ([https://www.ncbi.nlm.nih.gov/books/NBK9967/](https://www.ncbi.nlm.nih.gov/books/NBK9967/)). Having said this, I do know people who have changed their sex, not by changing their genetic makeup, but by deliberately deciding to transition from one sex to another through hormone therapy and surgery. I feel like this makes sex a very good feature to use when randomizing a group of people because you'll get a near 50/50 distribution. I placed Male at one end of the number line and Female at the other end and added a third, "N" sex for the event you choose to not use sex or if the person wishes to be grouped evenly among Males and Females.

**Comment by DreamShark-Bytes** [comment]
I'm disappointed to see you take this stance on the subject, sethblack. 
OP wasn't trying to discredit the fact that chromosomes exist. You've committed a strawman fallacy.

It's obvious this gift-exchange's requirements were put in place to ensure members of the family(s) gets to know everyone else. Between biological gender and pronouns, knowing and respecting someone's pronouns show you care enough to know them more. 

Honestly, I'd just remove gender/sex/pronouns from it all together. There are plenty of other weighted fields you use for randomization. If you feel you need this field for gift ideas and base those ideas off societal gender norms, there are much better ways. I suggest replacing this specific weighted field with something like a list of interests or a link to some equivalent. (Amazon wishlist, social media platforms, etc.)
Gifts are almost always about preference, and anyone can have any preference.  Whatever their chromosomes.  Unless you're family is only about giving gifts relating to biological phenomenon strictly tied to chromosomes. ( ex: Women, AFAB, in need some dedicated products? Men, AMAB, reaching a certain age and needing a coupon for a special doctor's visit?)
[[Definitions for the terms above]](https://www.nyp.org/documents/pps/cultural-competency/Understanding%20Disparities%20-%20LGBTQ%20Terminology.pdf)


Let me join in the sharing of resources: ConrtaPoints has some really insightful philosophies, this one in particular tackling **pronouns** (slight content warning, but hilariously entertaining): https://www.youtube.com/watch?v=9bbINLWtMKI
